<?php 


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_686e3d0e359d8',
    'title' => __('Alarm Module Configuration', 'event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_686e3d0f9bb14',
            'label' => __('Api Url', 'event-manager'),
            'name' => 'mod_alarm_api_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => __('The full URL containing the data to be displayed. Eg: https://domain.com/json/wp/v2/alarm/?per_page=100&page=1', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        1 => array(
            'key' => 'field_686e605f992b9',
            'label' => __('Icons', 'event-manager'),
            'name' => 'mod_alarm_icons_map',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('An icon can be mappeed to keywords in the title of the incident. If multiple matches is found, the first one will be used (be less specific towards the end).', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'table',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Add icon', 'event-manager'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_686e60af992ba',
                    'label' => __('keyword', 'event-manager'),
                    'name' => 'keyword',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_686e605f992b9',
                ),
                1 => array(
                    'key' => 'field_686e60bb992bb',
                    'label' => __('Icon', 'event-manager'),
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'icon',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_686e605f992b9',
                ),
            ),
        ),
        2 => array(
            'key' => 'field_686e663ac51ef',
            'label' => __('Severity Level Keyword (Level 1 - Low)', 'event-manager'),
            'name' => 'mod_alarm_severity_keyword_level_1',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => __('Low', 'event-manager'),
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        3 => array(
            'key' => 'field_686e6679c51f0',
            'label' => __('Severity Level Keyword (Level 2 - Medium)', 'event-manager'),
            'name' => 'mod_alarm_severity_keyword_level_2',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => __('Medium', 'event-manager'),
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        4 => array(
            'key' => 'field_686e66a0c51f1',
            'label' => __('Severity Level Keyword (Level 3 - High)', 'event-manager'),
            'name' => 'mod_alarm_severity_keyword_level_3',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => __('High', 'event-manager'),
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        5 => array(
            'key' => 'field_686e6de514f86',
            'label' => __('Color for low level', 'event-manager'),
            'name' => 'mod_alarm_severity_level_1_color',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui_on_text' => __('Primary', 'event-manager'),
            'ui_off_text' => __('Info', 'event-manager'),
            'ui' => 1,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-alarm-list',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/alarm-list',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));

}