<?php


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
        'key' => 'group_58d24fce7d85a',
        'title' => __('Disturbances', 'event-manager'),
        'fields' => array(
            0 => array(
                'key' => 'field_58d2501c0f51d',
                'label' => __('Activate', 'event-manager'),
                'name' => 'disturbnaces_enabled',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'message' => __('Enable disturbance messages', 'event-manager'),
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            1 => array(
                'key' => 'field_58d250070f51c',
                'label' => __('Api url', 'event-manager'),
                'name' => 'disturbances_api_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => __('The base url to the api alarm manager', 'event-manager'),
                'required' => 0,
                'conditional_logic' => array(
                    0 => array(
                        0 => array(
                            'field' => 'field_58d2501c0f51d',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            2 => array(
                'key' => 'field_58d26663441cc',
                'label' => __('Filter places', 'event-manager'),
                'name' => 'disturbances_places',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => __('You will first need to set your api url and save this page before places will be filled with alternatives. Leave blank to get disturbances from all places.', 'event-manager'),
                'required' => 0,
                'conditional_logic' => array(
                    0 => array(
                        0 => array(
                            'field' => 'field_58d2501c0f51d',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'multiple' => 1,
                'allow_null' => 0,
                'choices' => array(),
                'default_value' => array(),
                'ui' => 1,
                'ajax' => 0,
                'placeholder' => '',
                'return_format' => 'value',
                'create_options' => 0,
                'save_options' => 0,
                'allow_custom' => 0,
                'search_placeholder' => '',
            ),
            3 => array(
                'key' => 'field_58d250a30f51e',
                'label' => __('Output automatically', 'event-manager'),
                'name' => 'disturbances_output_automatically',
                'aria-label' => '',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    0 => array(
                        0 => array(
                            'field' => 'field_58d2501c0f51d',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'big' => __('Big disturbances', 'event-manager'),
                    'small' => __('Small disturbances', 'event-manager'),
                    'firelevel' => __('Firelevel', 'event-manager'),
                ),
                'default_value' => array(),
                'return_format' => 'value',
                'allow_custom' => 0,
                'allow_in_bindings' => 1,
                'layout' => 'vertical',
                'toggle' => 0,
                'save_custom' => 0,
                'custom_choice_button_text' => 'Add new choice',
            ),
            4 => array(
                'key' => 'field_58d2760046254',
                'label' => __('Output selector for big disturbance', 'event-manager'),
                'name' => 'output_selector_big_disturbance',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => __('CSS Selector for where to output big disturbances. Defaults to body.', 'event-manager'),
                'required' => 0,
                'conditional_logic' => array(
                    0 => array(
                        0 => array(
                            'field' => 'field_58d250a30f51e',
                            'operator' => '==',
                            'value' => 'big',
                        ),
                        1 => array(
                            'field' => 'field_58d2501c0f51d',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            5 => array(
                'key' => 'field_58d2764846255',
                'label' => __('Output selector for small disturbance', 'event-manager'),
                'name' => 'output_selector_small_disturbance',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => __('CSS Selector for where to output small disturbances. Defaults to body.', 'event-manager'),
                'required' => 0,
                'conditional_logic' => array(
                    0 => array(
                        0 => array(
                            'field' => 'field_58d250a30f51e',
                            'operator' => '==',
                            'value' => 'small',
                        ),
                        1 => array(
                            'field' => 'field_58d2501c0f51d',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            6 => array(
                'key' => 'field_6821ae0777ed7',
                'label' => __('Output selector for firelevel', 'event-manager'),
                'name' => 'output_selector_firelevel',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => __('CSS Selector for where to output small disturbances. Defaults to body.', 'event-manager'),
                'required' => 0,
                'conditional_logic' => array(
                    0 => array(
                        0 => array(
                            'field' => 'field_58d250a30f51e',
                            'operator' => '==',
                            'value' => 'small',
                        ),
                        1 => array(
                            'field' => 'field_58d2501c0f51d',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            0 => array(
                0 => array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'api-alarm-integration-disturbances',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));
}
